// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCco3hgJwND9vJNyizC3EPz4gkkkMSwI0M',
    appId: '1:1006466796903:web:e6cfa2410fb790ba7c73c2',
    messagingSenderId: '1006466796903',
    projectId: 'pokemon-flutter-9d000',
    authDomain: 'pokemon-flutter-9d000.firebaseapp.com',
    storageBucket: 'pokemon-flutter-9d000.firebasestorage.app',
    measurementId: 'G-0Y7F8BVSHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTKycwxPRDMcZFgbk5i0dCEx4Z2iAW0_s',
    appId: '1:1006466796903:android:659b5a5f6da201117c73c2',
    messagingSenderId: '1006466796903',
    projectId: 'pokemon-flutter-9d000',
    storageBucket: 'pokemon-flutter-9d000.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6YXgWZs8mfgNtsl52JyqjXN3JHv-ki7M',
    appId: '1:1006466796903:ios:618e8ce4c708dcdf7c73c2',
    messagingSenderId: '1006466796903',
    projectId: 'pokemon-flutter-9d000',
    storageBucket: 'pokemon-flutter-9d000.firebasestorage.app',
    iosBundleId: 'com.example.pokedexFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6YXgWZs8mfgNtsl52JyqjXN3JHv-ki7M',
    appId: '1:1006466796903:ios:618e8ce4c708dcdf7c73c2',
    messagingSenderId: '1006466796903',
    projectId: 'pokemon-flutter-9d000',
    storageBucket: 'pokemon-flutter-9d000.firebasestorage.app',
    iosBundleId: 'com.example.pokedexFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCco3hgJwND9vJNyizC3EPz4gkkkMSwI0M',
    appId: '1:1006466796903:web:f38deb40581b6f287c73c2',
    messagingSenderId: '1006466796903',
    projectId: 'pokemon-flutter-9d000',
    authDomain: 'pokemon-flutter-9d000.firebaseapp.com',
    storageBucket: 'pokemon-flutter-9d000.firebasestorage.app',
    measurementId: 'G-0KJMZX6T5Y',
  );
}
